# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170506_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expired_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
    ]
